oVirt/terraform-provider-ovirt

main.tf, ovirt/provider.go, ovirt/resource_disk.go, ovirt/resource_disk_attachment.go, ovirt/resource_vm.go
This PR adds a new resource `ovirt_disk_attachment` which represents a newly generated disk attachment after attaching a disk to a VM. `DiskAttachment` was previously defined by a field named `attached_disks` within resource `ovirt_vm`. It's more intuitive to regard the `DiskAttachment` as independent resource. Since create/update/delete a disk attachment should not change the configurations of `ovirt_vm` and `ovirt_disk` resources. 
Now your configurations of vm/disk/diskattachment may be as below:
```terraform
resource "ovirt_vm" "my_vm" {
name               = "my_vm_1"
cluster            = "Default"
authorized_ssh_key = "${file(pathexpand("~/.ssh/id_rsa.pub"))}"
template = "Blank"
}
resource "ovirt_disk" "my_disk_1" {
name              = "my_disk_1"
size              = 33687091200 …
```
=> Add resource ovirt_disk_attachment

main.tf, ovirt/data_source_datacenters.go, ovirt/provider.go
This pr is for implementing the new `ovirt_datacenters` data source. We could get a list of `datacenter` instances by the `name` argument. Currently the returned attributes includes only the `id`, `stats`, `local` and `quota_mode`.
=> Add new datasource: datacenters

main.tf, ovirt/provider.go, ovirt/resource_ovirt_datacenter.go, ovirt/resource_ovirt_network.go
Use the golang sdk of ovirt-engine v4.x to refactor the provider and existing resources/datacenter,resources/network.I tested OK with terraform apply and terraform destroy in my local oVirt-v4.2 dev environment.
=> Add support for datacenter and network

ovirt/data_source_ovirt_datacenters.go, ovirt/data_source_ovirt_datacenters_test.go, ovirt/provider.go, ovirt/provider_test.go
Since missing acceptance and unit tests, this pr adds basic support for acc testing of the `provider` and `data.ovirt_datacenters`. You could use `OVIRT_USERNAME=your-username OVIRT_PASSWORD=your-password OVIRT_URL=your-url TF_ACC=1 go test ./ovirt -v` to start acceptance testing. More tests would be added soon.
btw: also fixes a typo and adds `DefaultFunc` attribute definitions for `ResourceProvider` schemas.
=> Add initial acc test for the provider and the datasource of data.ovirt_datacenters

main.tf, ovirt/data_source_ovirt_common_schema.go, ovirt/data_source_ovirt_datacenters.go, ovirt/data_source_ovirt_datacenters_test.go
* add `{search = {criteria, max, case_sensitive}}` map attribute
* add `name_regex` attribute
* remove `name` attribute
This could add fully support for the `search criteria` described in [oVirt engine API Model](http://ovirt.github.io/ovirt-engine-api-model/4.3/#_searching)
BTW:
The original `name` filter could be replaced by:
```
search = {
criteria = "name = your-dc-name"
}
```
or 
```
name_regex = "your-dc-name"
```
```
TF_ACC=1 go test ./ovirt -v -run TestAccOvirtDataCentersDataSource_searchFilter
=== RUN   TestAccOvirtDataCentersDataSource_searchFilter
--- PASS: TestAccOvirtDataCentersDataSource_searchFilter (0.91s)
PASS
ok  	github.com/EMSL-MSC/terraform-provider-ovirt/ovirt	(cached)
```
=> data/ovirt_datacenters: Add support for more filter criteria

main.tf, ovirt/data_source_ovirt_networks.go, ovirt/data_source_ovirt_networks_test.go
* add {search = {criteria, max, case_sensitive}} map attribute
* add name_regex attribute
* remove name attribute
```
make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtNetworksDataSource'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtNetworksDataSource -timeout 180m
=== RUN   TestAccOvirtNetworksDataSource_nameRegexFilter
--- PASS: TestAccOvirtNetworksDataSource_nameRegexFilter (0.91s)
=== RUN   TestAccOvirtNetworksDataSource_searchFilter
--- PASS: TestAccOvirtNetworksDataSource_searchFilter (0.83s)
PASS
ok  	github.com/EMSL-MSC/terraform-provider-ovirt/ovirt	1.765s
```
=> data/ovirt_networks: Add support for more filter criteria

ovirt/data_source_ovirt_networks.go
Fixes #20 . 
* Use `Vlan()` instead of `MustVlan()` when getting the `vlan` attribute.
=> Check whether vlan exists when quering ovirt_networks Data Source

ovirt/resource_ovirt_network.go
Rename variables in `camelCase` that fits the go naming convention, instead of `snake_case`.
=> Fix unconventional code

ovirt/resource_ovirt_datacenter_test.go
* Add acceptance test for `ovirt_datacenter` Resource
```
make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtDataCenter_'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtDataCenter_ -timeout 180m
=== RUN   TestAccOvirtDataCenter_basic
--- PASS: TestAccOvirtDataCenter_basic (1.05s)
PASS
ok  	github.com/EMSL-MSC/terraform-provider-ovirt/ovirt	(cached)
```
> *BTW*: It takes the advantage of [new feature](https://github.com/imjoey/ovirt-engine-sdk-go/pull/120) of oVirt Go SDK that be able to identify the `NotFoundError`.
=> resource/datacenter: Add acc testing

ovirt/resource_ovirt_datacenter.go, ovirt/resource_ovirt_datacenter_test.go
* Remove `GetOK()` for required fields in update function
* If getting a datacenter returns back a `NotFoundError`, do `d.SetId("")` followed by `return nil` which is not an error.
```
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtDataCenter_ -timeout 180m
=== RUN   TestAccOvirtDataCenter_basic
--- PASS: TestAccOvirtDataCenter_basic (2.50s)
PASS
ok  	github.com/EMSL-MSC/terraform-provider-ovirt/ovirt	2.529s
```
=> Resource/ovirt_datacenter: Improve implementation and acc testing

README.md, main.tf, ovirt/data_source_ovirt_clusters.go, ovirt/data_source_ovirt_clusters_test.go, ovirt/provider.go
* Add new Data Source: ovirt_clusters
* Supported fields: id, name, datacenter_id, description
Output from acceptance test:
```
$ make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtClustersDataSource'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtClustersDataSource -timeout 180m
=== RUN   TestAccOvirtClustersDataSource_nameRegexFilter
--- PASS: TestAccOvirtClustersDataSource_nameRegexFilter (9.22s)
=== RUN   TestAccOvirtClustersDataSource_searchFilter
--- PASS: TestAccOvirtClustersDataSource_searchFilter (2.32s)
PASS
ok  	github.com/EMSL-MSC/terraform-provider-ovirt/ovirt	11.559s
```
=> New Data Source: ovirt_clusters

ovirt/provider.go, ovirt/resource_ovirt_vnic_profile.go, ovirt/resource_ovirt_vnic_profile_test.go
* Add new `ovirt_vnic_profile` Resource
* Add support for `name`, `network_id`, `migratable`, `port_mirroring` fields
Output from acceptance test:
```
make testacc TEST=./ovirt  TESTARGS='-run=TestAccOvirtVnicProfile_'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtVnicProfile_ -timeout 180m
=== RUN   TestAccOvirtVnicProfile_basic
--- PASS: TestAccOvirtVnicProfile_basic (2.69s)
PASS
ok      github.com/EMSL-MSC/terraform-provider-ovirt/ovirt      2.718s
```
=> Add New Resource: ovirt_vnic_profile

ovirt/resource_ovirt_vm.go
This is a step forward to fix #37 and the cause of issue and relevant solution is also described in #40 .
Changes in this pull request:
* Use `conn.FollowLink(vm.MustTemplate())` to retrieve the template attributes
=> resource/ovirt_vm: Fix bug that could not get the template name

README.md, main.tf, ovirt/resource_ovirt_disk.go, ovirt/resource_ovirt_vm.go, ovirt/resource_ovirt_vm_test.go
Partially Fixes issue #32. 
* Add `attached_disk` field in `ovirt_vm` resource
> Current `ovirt_disk_attachment` resource has lots of limitations. For example, the add/update/delete a disk attachment typically requires changing relevant VM lifecycle status, but it's confusing that the lifecycle operation is done by `ovirt_disk_attachment` Resource. The old  `ovirt_disk_attachment` Resource may mark as `deprecated` in the near future.
* Wait until the VM is up at the end of VM creation
> Thanks to the newly added `attached_disk` field. 😄 
* Add `vnic` field with the type of `schema.TypeSet`, to represent the vnic configurations for VM
* Rename `network_interace` field to `nic_configuration`, to represent the network initialization configurations
* Add …
=> resource/ovirt_vm: Improve the implementations and fix bugs

ovirt/resource_ovirt_vm.go, ovirt/resource_ovirt_vm_test.go
For issue #38 .
* Add `host_name`, `timezone`, `user_name`, `custom_script`, `dns_servers`, `dns_search` fields in `initialization` schema
* Improve acceptance test for these
Output from acceptance test:
```
make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtVM_'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtVM_ -timeout 180m
--- PASS: TestAccOvirtVM_basic (86.24s)
PASS
ok  	github.com/EMSL-MSC/terraform-provider-ovirt/ovirt	86.265s
```
=> resource/ovirt_vm: Add support for more initialization fields

ovirt/resource_ovirt_vm.go, ovirt/resource_ovirt_vm_test.go
Partially fixes issue #32 .
* Add support for updating a VM, currently support `attached_disk`, `vnic` and `inititialization` fields only.
* Add acceptance test for `resource/vm`.
```
make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtVM_'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtVM_ -timeout 180m
--- PASS: TestAccOvirtVM_basic (94.49s)
=== RUN   TestAccOvirtVM_attachedDisk
--- PASS: TestAccOvirtVM_attachedDisk (112.73s)
=== RUN   TestAccOvirtVM_vnic
--- PASS: TestAccOvirtVM_vnic (156.78s)
PASS
ok  	github.com/EMSL-MSC/terraform-provider-ovirt/ovirt	364.039s
```
=> Add support for updating attacheddisk/vnic/initialization fields

ovirt/resource_ovirt_disk.go, ovirt/resource_ovirt_disk_test.go
* Set `name` attribute to `ForceNew: false`
* Improve the support for updating disk
* Add acceptance testing for `resource/ovirt_disk`
* Fix the issue of can not update disk when `size` changed
* Fix the issue of can not delete disk when its attached VM is running
```
make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtDisk_'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtDisk_ -timeout 180m
=== RUN   TestAccOvirtDisk_basic
--- PASS: TestAccOvirtDisk_basic (313.16s)
PASS
ok  	github.com/EMSL-MSC/terraform-provider-ovirt/ovirt	313.184s```
=> resource/ovirt_disk: Improve funcionality and stability.

main.tf, ovirt/data_source_ovirt_vnic_profiles.go, ovirt/data_source_ovirt_vnic_profiles_test.go, ovirt/provider.go
Initial implementation of vnic_profiles data
* Initial implementation of vnic_profiles data
```
make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtVNicProfilesDataSource_'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtVNicProfilesDataSource_ -timeout 180m
=== RUN   TestAccOvirtVNicProfilesDataSource_nameRegexFilter
--- PASS: TestAccOvirtVNicProfilesDataSource_nameRegexFilter (2.40s)
PASS
ok      github.com/EMSL-MSC/terraform-provider-ovirt/ovirt      2.406s
steki@pc:~/go/src/github.com/EMSL-MSC/terraform-provider-ovirt> 
```
=> Data ovirt vnic profiles

README.md, main.tf, ovirt/provider.go, ovirt/resource_ovirt_disk.go, ovirt/resource_ovirt_vm.go, ovirt/resource_ovirt_vm_test.go, ovirt/resource_ovirt_vnic.go
For issue #52 .
* Add a new resource: `ovirt_vnic` and remove `vnic` attribute definition from `ovirt_vm`
> The new resource represents the nics which are explicitly attached to a VM by configurations.
* Use `block_device` attribute instead of `attached_disk` in resource`ovirt_vm`
> The new attribute represents the only bootable disk attached to this VM. It has the type of `List` and limited to one item at most. Noted that the disk described by this attribute in backend is **NOT** managed by Terraform. If you want to manage disks attached in more depth, please use resource `ovirt_disk_attachment`.
* Replace `template` with `template_id` in resource `ovirt_vm`
Basically, since the disks and nics of VM based on a template are implicitly created, this …
=> resource/ovirt_vm: Redesign the disks and vnics of VM resource

ovirt/resource_ovirt_vm.go, ovirt/resource_ovirt_vm_test.go
For issue #38 .
* Set `useCloudInit` according to the `initialization` attributes on starting a VM
> Currently only the `cloud-init` for Linux VM is supported, the support for `sysprep` for Windows VM will be soon.
* Optimize the acc test of resource `ovirt_vm`
```
$ make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtVM_'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtVM_ -timeout 180m
=== RUN   TestAccOvirtVM_blockDevice
--- PASS: TestAccOvirtVM_blockDevice (231.33s)
=== RUN   TestAccOvirtVM_template
--- PASS: TestAccOvirtVM_template (210.88s)
=== RUN   TestAccOvirtVM_vnic
--- PASS: TestAccOvirtVM_vnic (101.07s)
PASS
ok …
```
=> Set useCloudInit parameter when starting VM

README.md, ovirt/resource_ovirt_disk.go, ovirt/resource_ovirt_disk_test.go
* Use GiB to represent the Disk size
* Make acc test more intuitive and simple
```
make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtDisk_basic'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtDisk_basic -timeout 180m
=== RUN   TestAccOvirtDisk_basic
--- PASS: TestAccOvirtDisk_basic (138.02s)
PASS
ok      github.com/imjoey/terraform-provider-ovirt/ovirt        138.049s
```
=> resource/ovirt_disk: Use GiB as the unit of Disk size

ovirt/resource_ovirt_disk_attachment.go, ovirt/resource_ovirt_disk_attachment_test.go
* Optimize the creation logic
* Add support for updating
* Add acc tests
```
make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtDiskAttachment_basic'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtDiskAttachment_basic -timeout 180m
=== RUN   TestAccOvirtDiskAttachment_basic
--- PASS: TestAccOvirtDiskAttachment_basic (13.17s)
PASS
ok      github.com/imjoey/terraform-provider-ovirt/ovirt        13.201s
```
=> r/ovirt_disk_attachment: optimize the logic and add acc testing.

ovirt/resource_ovirt_disk_attachment.go, ovirt/resource_ovirt_disk_attachment_test.go
Fixes #67 .
* Set `logical_name` to be `Required`
* Minor changes of related codes
```
make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtDiskAttachment_basic'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtDiskAttachment_basic -timeout 180m
=== RUN   TestAccOvirtDiskAttachment_basic
--- PASS: TestAccOvirtDiskAttachment_basic (12.82s)
PASS
ok      github.com/imjoey/terraform-provider-ovirt/ovirt        12.854s
```
=> Set logic_name to Required instead of Optional.

ovirt/resource_ovirt_disk_attachment.go, ovirt/resource_ovirt_disk_attachment_test.go
Related with issue #67 
* Remove the `logical_name` attribute
The `logical_name` attribute could not be retrieved via API before the guest agent installed in VM. So in this case, Terraform is not able to correctly manage the attribute, which definitely breaks the uniformity. Since `logical_name` could be gracefully managed by oVirt, just remove it now. A more ideal solution will be provided in future.
```
OVIRT_USERNAME=admin@internal OVIRT_PASSWORD=qwer1234 OVIRT_URL=https://10.1.161.222/ovirt-engine/api make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtDiskAttachment_basic'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtDiskAttachment_basic -timeout 180m
=== …
```
=> r/ovirt_disk_attachment: Remove logical_name attribute

Gopkg.lock, Gopkg.toml, vendor/gopkg.in/imjoey/go-ovirt.v4/connection.go, vendor/gopkg.in/imjoey/go-ovirt.v4/services.go
* Update the version of oVirt Go SDK from v4.0.3 to v4.0.4
This is the prerequisite to add support for specifying headers of API connection in provider configurations, see #72 for details.
=> Update go sdk to 4.0.4

ovirt/provider.go
This PR is aimed at making the provider able to connect to oVirt APIs as a non-admin user.
Please see https://github.com/imjoey/ovirt-engine-sdk-go/pull/127 for further details.
=> Add headers param to oVirt connection

GNUmakefile, README.md, website/docs/d/clusters.html.markdown, website/docs/d/datacenters.html.markdown, website/docs/d/disks.html.markdown, website/docs/d/networks.html.markdown, website/docs/d/storagedomains.html.markdown, website/docs/d/vnic_profiles.html.markdown, website/docs/index.html.markdown, website/docs/r/datacenter.html.markdown, website/docs/r/disk.html.markdown, website/docs/r/disk_attachment.html.markdown, website/docs/r/network.html.markdown, website/docs/r/vm.html.markdown, website/docs/r/vnic.html.markdown, website/docs/r/vnic_profile.html.markdown, website/ovirt.erb
Aims at #73 to add more examples and documents.
* Add basic `website` infrastructure
* Add `website` and `website-test` targets in `GNUmakefile`
* Add documents for provider
* Add documents for all of the existing resources
* Add documents for all of the existing data sources
> Now in my local dev environment, I encounter the issue https://github.com/hashicorp/terraform-website/issues/3 . Currently I've no idea how to get a workaround, in order to provider documents ASAP, I just merge it blindly. If the website codes have errors, please open issues. 😄
=> doc: Add website

Gopkg.lock, Gopkg.toml, vendor/gopkg.in/imjoey/go-ovirt.v4/connection.go, vendor/gopkg.in/imjoey/go-ovirt.v4/readers.go, vendor/gopkg.in/imjoey/go-ovirt.v4/services.go, vendor/gopkg.in/imjoey/go-ovirt.v4/types.go, vendor/gopkg.in/imjoey/go-ovirt.v4/version.go, vendor/gopkg.in/imjoey/go-ovirt.v4/writers.go
See https://github.com/imjoey/ovirt-engine-sdk-go/pull/131 and https://github.com/imjoey/ovirt-engine-sdk-go/pull/130 for the details of new release go-ovirt sdk.
=> Update go-sdk dependency library to v4.0.5

ovirt/resource_ovirt_vnic_test.go
Fixes #88 .
* Add basic acceptance testing
```
make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtVnic_basic'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtVnic_basic -timeout 180m
=== RUN   TestAccOvirtVnic_basic
--- PASS: TestAccOvirtVnic_basic (6.14s)
PASS
ok      github.com/imjoey/terraform-provider-ovirt/ovirt        6.168s
```
=> Add basic accpentance testing for resource ovirt_vnic.

ovirt/resource_ovirt_network.go, ovirt/resource_ovirt_network_test.go
Fixes #86 .
* Add acceptance testing for `ovirt_network` resource
* Remove some trailing punctuations in error message
```
make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtNetwork_basic'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtNetwork_basic -timeout 180m
=== RUN   TestAccOvirtNetwork_basic
--- PASS: TestAccOvirtNetwork_basic (1.43s)
PASS
ok      github.com/imjoey/terraform-provider-ovirt/ovirt        1.454s
```
=> resource/ovirt_network: Add basic acceptance testing

ovirt/resource_ovirt_vm.go, ovirt/resource_ovirt_vm_test.go
* Add `high_availability` param to `ovirt_vm` 
* Add possibility to create VM nics upon VM creation; this prevents nics to be added after VM has been launched, avoiding a race condition that let cloud-init run before network cards have been attached to the VM
@imjoey I'm unable to run acceptance tests at the moment, as I don't have access to my oVirt test deployment. Could you please help? Thanks
=> Add high_availability and nics on creation features

ovirt/provider.go, ovirt/resource_ovirt_storage_domain.go, ovirt/resource_ovirt_storage_domain_test.go
Fixes #85 .
* Add new resource: `ovirt_storage_domain`
* Add support for `nfs` storage type
> Note: Currently updating a `ovirt_storage_domain` is not supported yet.
```
make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtStorageDomain_nfs'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtStorageDomain_ -timeout 180m
=== RUN   TestAccOvirtStorageDomain_nfs
--- PASS: TestAccOvirtStorageDomain_nfs (91.85s)
PASS
ok      github.com/imjoey/terraform-provider-ovirt/ovirt        91.889s
```
=> New resource: ovirt_storage_domain

ovirt/data_source_ovirt_authzs.go, ovirt/data_source_ovirt_authzs_test.go, ovirt/provider.go
Fixes #96 .
* Add new data source `ovirt_authzs`
Note that using `ovirt_authzs` as the name of new data source which represents the `Domain` instead of `ovirt_domains` is to coincide with the one in Ansible oVirt Module [1](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/ovirt/ovirt_user.py#L45).
```
$ make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtAuthzsDataSource_'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtAuthzsDataSource_ -timeout 180m
=== RUN   TestAccOvirtAuthzsDataSource_nameRegexFilter
--- PASS: TestAccOvirtAuthzsDataSource_nameRegexFilter (1.02s)
PASS
ok …
```
=> New Data Source: ovirt_authzs

ovirt/data_source_ovirt_authzs.go, ovirt/data_source_ovirt_authzs_test.go, ovirt/data_source_ovirt_common_schema.go
* Add new `dataSourceSearchSchemaWith()` function
* Add missing `search.max` field support for data source `ovirt_authzs`
```
$ make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtAuthzsDataSource_'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtAuthzsDataSource_ -timeout 180m
=== RUN   TestAccOvirtAuthzsDataSource_nameRegexFilter
--- PASS: TestAccOvirtAuthzsDataSource_nameRegexFilter (2.03s)
PASS
ok  	github.com/imjoey/terraform-provider-ovirt/ovirt	2.058s
```
=> Add support specifying subfields explicitly for search fields

ovirt/data_source_ovirt_users.go, ovirt/data_source_ovirt_users_test.go, ovirt/provider.go
Fixes #95 .
* Add new data source `ovirt_users`
* Add acceptance testings for it
```
$ make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtUsersDataSource_'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtUsersDataSource_ -timeout 180m
=== RUN   TestAccOvirtUsersDataSource_nameRegexFilter
--- PASS: TestAccOvirtUsersDataSource_nameRegexFilter (2.25s)
=== RUN   TestAccOvirtUsersDataSource_searchFilter
--- PASS: TestAccOvirtUsersDataSource_searchFilter (3.17s)
PASS
ok  	github.com/imjoey/terraform-provider-ovirt/ovirt	5.450s
```
=> New Data Source: ovirt_users

ovirt/provider.go, ovirt/resource_ovirt_mac_pool.go, ovirt/resource_ovirt_mac_pool_test.go, ovirt/utils.go
Fixes #104 .
* Add new resource `ovirt_mac_pool`
```
$ make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtMacPool_'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtMacPool_ -timeout 180m
=== RUN   TestAccOvirtMacPool_basic
--- PASS: TestAccOvirtMacPool_basic (1.71s)
PASS
ok  	github.com/imjoey/terraform-provider-ovirt/ovirt	1.738s
```
=> New Resource: ovirt_mac_pool

ovirt/data_source_ovirt_mac_pools.go, ovirt/data_source_ovirt_mac_pools_test.go, ovirt/provider.go
Fixes #108 .
* Add new data source `ovirt_mac_pools`
```
$ make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtMacPoolsDataSource_'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtMacPoolsDataSource_ -timeout 180m
=== RUN   TestAccOvirtMacPoolsDataSource_nameRegexFilter
--- PASS: TestAccOvirtMacPoolsDataSource_nameRegexFilter (0.75s)
PASS
ok      github.com/imjoey/terraform-provider-ovirt/ovirt        0.776s
```
=> New Data Source: ovirt_mac_pools

Gopkg.lock, Gopkg.toml, vendor/gopkg.in/imjoey/go-ovirt.v4/version.go
* Update the dependency of oVirt go sdk to the latest stable version `4.2.1`
=> Update oVirt go sdk to 4.2.1

ovirt/resource_ovirt_vm.go, ovirt/resource_ovirt_vm_test.go
Fixes #122 .
* Add a new `clone` option, which could enable user to specify the
clone parameter when creating a VM from template. If clone is
true, the created VM will not depend on the template. The default
value is false.
* Add acceptance test for this new option
```
$ make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtVM_templateClone'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtVM_templateClone -timeout 180m
=== RUN   TestAccOvirtVM_templateClone
--- PASS: TestAccOvirtVM_templateClone (112.19s)
PASS
ok  	github.com/imjoey/terraform-provider-ovirt/ovirt	112.205s
```
=> resource/ovirt_vm: Add clone option support for creating VM from template independently

README.md, ovirt/data_source_ovirt_hosts.go, ovirt/data_source_ovirt_hosts_test.go, ovirt/provider.go
* Add new data source `ovirt_hosts` support for querying existing hosts
* Add acceptance testing for `ovirt_hosts`
```
$ make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtHostsDataSource_*'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtHostsDataSource_* -timeout 180m
=== RUN   TestAccOvirtHostsDataSource_nameRegexFilter
--- PASS: TestAccOvirtHostsDataSource_nameRegexFilter (0.78s)
=== RUN   TestAccOvirtHostsDataSource_searchFilter
--- PASS: TestAccOvirtHostsDataSource_searchFilter (0.68s)
PASS
ok      github.com/imjoey/terraform-provider-ovirt/ovirt        1.486s
```
=> New Data Source: ovirt_hosts

ovirt/resource_ovirt_vm.go
The VM (HostedEngine) may has no `original_template attribute`, which
may lead to panics when reading a VM resource. See #139 for bug details.
This pr improved the codes logic to fix the issue.
Fixes #139 
* Use `Originaltemplate()` to retrieve the attribute instead of its `MustOriginaltemplate()` counterpart
```
$ make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtVM_templateClone'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtVM_templateClone -timeout 180m
=== RUN   TestAccOvirtVM_templateClone
--- PASS: TestAccOvirtVM_templateClone (101.93s)
PASS
ok  	github.com/imjoey/terraform-provider-ovirt/ovirt	101.960s
```
=> Fix panics due to no VM original_template attribute

renovate.json
In accordance to the discussions in #151 , we decide to remove the integration with renovate-bot which deal with the update of deps automatically. We believe a fine-grained control on updating deps will always keep the project stable, simple and production-ready.
* Remove the configuration files of renovate-bot
=> Uninstall renovate-bot integration

.travis.yml, GNUmakefile
* Add extra flags for go command to enable go modules and force to use go code in `vendor`.
* Eliminate the legacy `govendor` package
=> Set Go flags and remove the legacy govendor package

README.md, ovirt/provider.go, ovirt/resource_ovirt_snapshot.go, ovirt/resource_ovirt_snapshot_test.go, website/docs/r/snapshot.html.markdown
Fixes #105 .
* Add support for new resource ovirt_snapshot, which is to manage a snapshot of a vm
* Add acceptance testing for this new resource
* Add docs in site associated with this new resource
```
$ make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtSnapshot_basic'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtSnapshot_basic -timeout 180m
=== RUN   TestAccOvirtSnapshot_basic
--- PASS: TestAccOvirtSnapshot_basic (109.37s)
PASS
ok      github.com/ovirt/terraform-provider-ovirt/ovirt 109.391s
```
=> New Resource: ovirt_snapshot

ovirt/data_source_ovirt_authzs_test.go, ovirt/data_source_ovirt_clusters_test.go, ovirt/data_source_ovirt_datacenters_test.go, ovirt/data_source_ovirt_disks_test.go, ovirt/data_source_ovirt_hosts_test.go, ovirt/data_source_ovirt_mac_pools_test.go, ovirt/data_source_ovirt_networks_test.go, ovirt/data_source_ovirt_storagedomains_test.go, ovirt/data_source_ovirt_users_test.go, ovirt/data_source_ovirt_vms_test.go, ovirt/data_source_ovirt_vnic_profiles_test.go, ovirt/resource_ovirt_cluster_test.go, ovirt/resource_ovirt_datacenter_test.go, ovirt/resource_ovirt_disk_attachment_test.go, ovirt/resource_ovirt_disk_test.go, ovirt/resource_ovirt_host_test.go, ovirt/resource_ovirt_mac_pool_test.go, ovirt/resource_ovirt_network_test.go, ovirt/resource_ovirt_snapshot_test.go, ovirt/resource_ovirt_storage_domain_test.go, ovirt/resource_ovirt_tag_test.go, ovirt/resource_ovirt_user_test.go, ovirt/resource_ovirt_vm_test.go, ovirt/resource_ovirt_vnic_profile_test.go, ovirt/resource_ovirt_vnic_test.go
Fixes #159 .
* Set 2 whitespaces as the indentation for HCL code snippets
* Each config option is aligned vertically by equal sign
=> Format the HCL code snippets defined in acceptance tests

ovirt/resource_ovirt_disk_attachment.go, ovirt/resource_ovirt_disk_attachment_test.go
Fixes #161 
* Parse the `rs.Primary.ID` into respective ID of vm and disk-attachment and then check the existence of the specific disk-attachment
* Change the parameters of function `getVMIDAndDiskID()` to better fit for general purpose
```
$ make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtDiskAttachment_basic'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtDiskAttachment_basic -timeout 180m
=== RUN   TestAccOvirtDiskAttachment_basic
--- PASS: TestAccOvirtDiskAttachment_basic (2.66s)
PASS
ok      github.com/ovirt/terraform-provider-ovirt/ovirt 2.695s
```
=> resource/ovirt_disk_attachment: Correct checking if a disk attachment has been destroyed

ovirt/resource_ovirt_disk_attachment.go, ovirt/resource_ovirt_disk_attachment_test.go, ovirt/resource_ovirt_snapshot.go, ovirt/resource_ovirt_snapshot_test.go, ovirt/resource_ovirt_vnic.go, ovirt/resource_ovirt_vnic_test.go, ovirt/utils.go, ovirt/utils_test.go
* Add a general helper function named `parseResourceID` to parse combined resource ID
* Remove the legacy `getXXIDAndYYID` functions and use new `parseResourceID` function instead
* Add test case for this new function
Output from testing:
```
$ go test ./ovirt -run "TestParseResourceID" -v
=== RUN   TestParseResourceID
--- PASS: TestParseResourceID (0.00s)
PASS
ok  	github.com/ovirt/terraform-provider-ovirt/ovirt	0.020s
```
=> Add general purpose function to parse resource ID

website/docs/d/clusters.html.markdown, website/docs/d/datacenters.html.markdown, website/docs/d/disks.html.markdown, website/docs/d/networks.html.markdown, website/docs/d/storagedomains.html.markdown, website/docs/d/vnic_profiles.html.markdown, website/docs/index.html.markdown, website/docs/r/vm.html.markdown
Along with the new Terraform v0.12, Terraform also introduces the recommended [Idiomatic Style Conventions](https://www.terraform.io/docs/configuration/style.html) for HCL languages. Besides the HCL explicitly defined in `.tf` and . `.tfvars`, the inline HCLs in docs should also follow that rule. 
This PR is trying to convert all the existing inline HCL codes into the canonical format. I made a tool https://github.com/imjoey/md-code-formatter for doing this.
=> Format inline HCL codes in docs

ovirt/resource_ovirt_vm.go, ovirt/resource_ovirt_vm_test.go
Issue #166 .
* After updating a VM, keep its original status without starting it
* Improve the acceptance test cases for resource vm
```
$ make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtVM_basic'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtVM_basic -timeout 180m
--- PASS: TestAccOvirtVM_basic (94.16s)
PASS
ok      github.com/ovirt/terraform-provider-ovirt/ovirt 94.183s
```
=> resource/ovirt_vm: Do not change VM status after updating

ovirt/resource_ovirt_datacenter.go, ovirt/resource_ovirt_datacenter_test.go, website/docs/r/datacenter.html.markdown
* Add support for new `status` field marked as `computed`
* Make acceptance testing for the new field
* Add relevant docs
```
$ make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtDataCenter_basic'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtDataCenter_basic -timeout 180m
=== RUN   TestAccOvirtDataCenter_basic
--- PASS: TestAccOvirtDataCenter_basic (1.43s)
PASS
ok      github.com/ovirt/terraform-provider-ovirt/ovirt 1.453s
...
```
=> resource/ovirt_datacenter: Make the status field exportable

README.md, ovirt/data_source_ovirt_nics.go, ovirt/data_source_ovirt_nics_test.go, ovirt/provider.go, website/docs/d/nics.html.markdown
* Add support for new data source `ovirt_nics` to provide the details
about the NICs of a VM, or a Template (**not supported yet**)
* Add acceptance testing for this new data source
* Add relevant docs
```
$ make testacc  TEST=./ovirt TESTARGS='-run=TestAccOvirtNicsDataSource_nameRegexFilter'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtNicsDataSource_nameRegexFilter -timeout 180m
=== RUN   TestAccOvirtNicsDataSource_nameRegexFilter
--- PASS: TestAccOvirtNicsDataSource_nameRegexFilter (0.55s)
PASS
ok      github.com/ovirt/terraform-provider-ovirt/ovirt 0.576s
```
=> New Data Source: ovirt_nics

.travis.yml, README.md
* Update README with recommendation to go1.12, as well as to using `go module`
* Update go version to 1.12.x in travis.ci
=> docs: Update to using go version 1.12+

README.md, ovirt/data_source_ovirt_template.go, ovirt/data_source_ovirt_template_test.go, ovirt/provider.go, website/docs/d/templates.html.markdown
Fixes #182 
* Add support for new data source `ovirt_template`
* Add acceptance testing for `ovirt_template`
* Add docs for `ovirt_template`
```
$ make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtTemplatesDataSource_*'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtTemplatesDataSource_* -timeout 180m
=== RUN   TestAccOvirtTemplatesDataSource_nameRegexFilter
--- PASS: TestAccOvirtTemplatesDataSource_nameRegexFilter (0.73s)
=== RUN   TestAccOvirtTemplatesDataSource_searchFilter
--- PASS: TestAccOvirtTemplatesDataSource_searchFilter (0.58s)
PASS
ok      github.com/ovirt/terraform-provider-ovirt/ovirt 1.651s
```
=> Add support for data source ovirt_template

ovirt/resource_ovirt_vm.go, ovirt/resource_ovirt_vm_test.go, website/docs/r/vm.html.markdown
Fixes #189
* add boot_devices to resource
* add populating boot_devices during reading resource
* implement mapping to ovirt API for boot devices
```
make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtVM_noBootDevice'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtVM_noBootDevice -timeout 180m
=== RUN   TestAccOvirtVM_noBootDevice
--- PASS: TestAccOvirtVM_noBootDevice (142.48s)
PASS
ok      github.com/ovirt/terraform-provider-ovirt/ovirt 142.500s
make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtVM_bootDevice'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtVM_bootDevice -timeout 180m
=== RUN …
```
=> implement boot devices for vms

ovirt/resource_ovirt_image_transfer.go
Fixes #187 
* Resets file cursor after writing the temp image file for the next read.
```
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtDataCenter_ -timeout 180m
=== RUN   TestAccOvirtDataCenter_basic
--- PASS: TestAccOvirtDataCenter_basic (1.51s)
PASS
ok      github.com/ovirt/terraform-provider-ovirt/ovirt 1.524s
...
```
=> Fix immediate EOF on reads for image transfers via http(s)

examples/vm/main.tf, ovirt/resource_ovirt_vm.go
Motivation
New VMs inherit their bootable disk attachement details from the template. A RHEL/RHCOS, CentOS, Ubuntu or any os would likely want to override those on creation. We want a bigger disk for some VMs, different driver, and do that in one-shot definition, without needing to go and create disk attachment resources and then terraform-refresh them.
Modification
The existing 'block_device' element in vm resource can take 'disk_id' optionally instead of mandatory. When the `disk_id` is lacking, the bootable disk that is attached to this newly created vm is updated with the details in `block_device`.
Result
We have a template with OS disk of 16Gib.
We want to create a new VM and extend the OS disk to 120Gib:
```hcl
resource "ovirt_vm" "masters" {
...
template_id = xyz  // the template …
```
=> Override disk attachment on VM resource create

examples/vm/main.tf, ovirt/resource_ovirt_vm.go, website/docs/d/vms.html.markdown
Add  instance_type support for ovirt_vm:
```
resource "ovirt_vm" "test" {
...
instance_type_id = "<uuid of an instance type>"
}
```
To get a list of instance type of the system
`curl https://ovirt-engine-fqdn/ovirt-engine/api/instancetypes | jq '.[][]|.id,.name'`
=> Additions to VM resource

ovirt/resource_ovirt_vm.go
Creating a Vm with empty instance type is allowed, and the resource read need to handle a case where its missing.
=> Handle empty instance type Creating a Vm with empty instance type is allowed, and the resource read need to handle a case where its missing.

ovirt/resource_ovirt_vm.go
Creating a Vm with empty instance type is allowed, and the resource read
need to handle a case where its missing.
=> Handle empty instance type

ovirt/resource_ovirt_image_transfer.go
Fixing a panic in case the an OPTIONS request to the host url fails
=> image_transfer: failed OPTIONS request will panic

ovirt/resource_ovirt_vm.go, website/docs/d/vms.html.markdown, website/docs/r/vm.html.markdown
The default behavior is that when we create a VM with the terraform provider the VM is automatically started.
We want the ability to create a VM and not start it.
Adding a flag to indicate if we want to start the VM on creation.
Signed-off-by: Gal-Zaidman <gzaidman@redhat.com>
=> Add auto_start flag to ovirt_vm resource

ovirt/resource_ovirt_image_transfer.go, ovirt/resource_ovirt_vm_template.go
We noticed on OCP on RHV that sometimes we hit the timeout on the template creation or the image transfer.
This patch increases the timeout to 20m on create and update.
Signed-off-by: Gal-Zaidman <gzaidman@redhat.com>
=> increase template and image transfer timeout

ovirt/resource_ovirt_image_transfer.go, ovirt/resource_ovirt_vm_template.go
This reverts commit 17adf8398f24168619d28aadf4729d05c095c7b0.
there is a way to override the default timeout from the resource definition
Fixes #0000
* Change 1
* Change 2
```
...
```
=> Revert "increase template and image transfer timeout"

ovirt/resource_ovirt_vm.go
Fixes both:
* not defining the OS to cause VMs to be recreated on future runs of TF. I've seen a similar change by  @pavel-z1 in a different PR.
* OS not being updated in the Update function
=> Allow OS to be updated rather than recreating VM

ovirt/resource_ovirt_vm.go
Fixes #223 
* Delete disks attach to a VM we create by cloning a template. Otherwise these are left behind when the VM is deleted. This is in line with the current logic where we delete all disks attached to a VM if it was made from a template.
=> Set detachOnly to false when deleting template clones

examples/vm/main.tf, ovirt/resource_ovirt_vm.go
Add possibility to setup Disk Alias during deploy VM from Template
Example:
```
resource "ovirt_vm" "vm_name" {
...
block_device {
interface      = "virtio_scsi"
alias          = "vm_name_Disk1"
}
initialization {
...
}
```
=> Disk Alias configuration during deploy VM from Template

ovirt/provider.go, ovirt/resource_ovirt_affinity_group.go, ovirt/resource_ovirt_affinity_group_test.go
Partly completes #199. I didn't see the purpose of it as a data source (as you can't use the result as input for any other resource) but it should be easy to add, to further complete #199.
Further extensions:
- priority
- labels
* Add affinity group resource
```
=== RUN   TestAccOvirtAffinityGroup_basic
--- PASS: TestAccOvirtAffinityGroup_basic (11.43s)
PASS
...
```
=> Add Affinity Group resource

ovirt/resource_ovirt_disk.go
* Don't throw a 404 Not Found error when trying to read a disk that doesn't exist.
Currently, if a disk is deleted outside of terraform but is still within TF state, the provider will throw a 404 error as is tries to read the disk by ID and fails.
This simply catches this and returns nil to result in the expected behaviour - TF tries to recreate the disk.
=> Fix throwing a 404 error if we cannot find a disk by ID

.github/workflows/release.yml, .goreleaser.yml
As taken from terraform-provider-scaffolding
This workflow creates a draft release with all the required binary artifacts that the hashicorp registry requires. It requires an admin to set a github secret called GPG_FINGERPRINT which is the gpg key with which the binaries will be signed
This workflow is a required step for achieving #230
=> import of release workflow from provider scafolding

CHANGELOG.md
Generated a changelog for the newly to be released version. I selected 0.5.0 at random but am happy to adjust. the changelog was generated using github-changelog-generator/github-changelog-generator which uses tags to categorize pr's and ticket into categories.
=> preparing for v0.5.0 release

ovirt/resource_ovirt_cluster.go, ovirt/resource_ovirt_vm.go
This change will let the user create cluster with KSM property, by
default set to disabled.
On High Performance type VM it will set partial high performance
settings such: disable ballooning, serial console and removing the
graphical console, making the VM headless.
Bug-Url: https://bugzilla.redhat.com/1848922
Signed-off-by: Liran Rotenberg <lrotenbe@redhat.com>
=> Set high performance properties on VM creation

.github/workflows/pr.yml, .github/workflows/release.yml, .goreleaser.yml
This change removes the legacy GPG signing (to be re-added later) for releases and adds builds for branch pushes and PRs.
=> Build system

ovirt/resource_ovirt_host.go
Fixes #244
* Fixes issue: #244 root_password visible in terraform plan
```
...
```
=> Fixes #244: root_password visible in terraform plan

docs/resources/vm.md, go.mod, go.sum, ovirt/resource_ovirt_vm.go, vendor/github.com/ovirt/go-ovirt/CHANGES.adoc, vendor/github.com/ovirt/go-ovirt/readers.go, vendor/github.com/ovirt/go-ovirt/services.go, vendor/github.com/ovirt/go-ovirt/types.go, vendor/github.com/ovirt/go-ovirt/writers.go, vendor/modules.txt
This patch will introduce the AutoPinningPolicy. This will allow VMs to
automatically get the configuration for CPUs and NUMA. For high
performance VMs, it will be automatically set to `existing` policy.
- `adjust` policy will change the CPU topology based on the host
topology, will set the vCPU pinning and NUMA nodes.
- `existing` policy will set the vCPU pinning and NUMA nodes with the
existing VM CPU topology.
- `disabled` won't do nothing, and can used to disable the default high
performance VM policy value.
Each VM using a policy will be pinned to each host within the cluster
with allowed migration. Once the user will add a host, he needs to
update the VMs, adding the new host to the pinned hosts.
This patch bump the go-ovirt SDK.
Signed-off-by: Liran Rotenberg <lrotenbe@redhat.com>
=> introduce auto pinning policy

.travis.yml, go.mod, ovirt/resource_ovirt_vm.go, ovirt/utils.go, vendor/modules.txt
This change adds the ability to specify affinity groups for a VM upon creation.
It is required because once a VM is created and started then if it is added to an affinity group it is just "best effort".
If it is added to the affinity group before it is started then the affinity group rules will apply.
I'll open a separate PR for the update and read flow because I suspect it will take more time to implement
=> Add affinity groups field to VM object and bump go to v1.15

ovirt/resource_ovirt_affinity_group.go
We should allow creating affinity groups rules with no VM list.
This is needed in case we want to create the VMs later to join the affinity group.
The current state is that the affinity group rule will just not get created and terraform will not notify on that
=> Allow creating affinity group rules without VMs

docs/resources/vm.md, ovirt/resource_ovirt_vm.go
This patch will allow setting the `hugepages` custom property to a VM.
The values for 86_64 arch are `2048` (2 MiB) and `1048576` (1 GiB). The
host should have enough hugepages with the right size in order to use
this value.
Signed-off-by: Liran Rotenberg <lrotenbe@redhat.com>
=> add explicit hugepages support to vm

docs/resources/vm.md, ovirt/resource_ovirt_vm.go
Since ovirt 4.4.7, ovirt changed the auto pinning policies naming(UI).
This patch will allow using the new names to align with it. The
previous names are staying to support backward compatibilty.
=> use the new auto pinning naming

ovirt/provider.go
This patch resolves issue #268 [1] by setting the insecure default value
to false instead of an empty string.
[1] https://github.com/oVirt/terraform-provider-ovirt/issues/268
Signed-off-by: Eli Mesika <emesika@redhat.com>
Fixes #0000
* Change 1
* Change 2
```
...
```
=> set insecure default value to false

.github/workflows/compile-ocp-installer.yml, tr-ocp-installer.spec
This patch adds the terraform provider go packages needed for terraform
init command as plugin sources.
Signed-off-by: emesika <emesika@redhat.com>
...
...
...
=> Adding terraform provider packages

.github/workflows/compile-ocp-installer.yml
Generate only tr-suite-master binaries rpm to save storage on engine VM.
Signed-off-by: Eli Mesika <emesika@redhat.com>
...
...
...
=> Do not generate src package

.github/tr-master-suite-trigger.yaml
Adds a tr-suite-master trigger file in order to run OST on
tr-suite-master suite using the passed PR URL and distro
Signed-off-by: Eli Mesika emesika@rehat.com
...
...
...
=> Adding a tr-suite-master trigger file

CONTRIBUTING.md
Added a missing single quote
yes
yes
=> added missing single quote

ovirt/resource_ovirt_disk.go, ovirt/resource_ovirt_disk_attachment.go, ovirt/resource_ovirt_disk_attachments.go, ovirt/resource_ovirt_tag.go, ovirt/resource_ovirt_vm_start.go
Fixing two bugs across multiple resources:
1. The `p.client` was used without the `WithContext` call in multiple places.
2. When an `ENotFound` error was encountered, the data ID was not set to empty, instead, an error was returned.
This PR supersedes #355.
Yes
Yes
=> Fixed TF state management and context bugs

docs/resources/vm.md, ovirt/resource_ovirt_vm.go, ovirt/resource_ovirt_vm_test.go
This PR adds the `os_type` parameter to the `ovirt_vm` resource.
Yes
Yes
=> Fixes #363: Add os_type parameter to ovirt_vm

docs/resources/vm.md, ovirt/resource_ovirt_vm.go, ovirt/resource_ovirt_vm_test.go
This PR adds placement policy options to the `ovirt_vm` resource as requested in #366.
Yes
Yes
=> Fixes #366: Added placement policy options to ovirt_vm

go.mod, go.sum, ovirt/resource_ovirt_vm.go, ovirt/resource_ovirt_vm_test.go
This PR fixes #361 and adds memory handling. Requires oVirt/go-ovirt-client#206 and oVirt/go-ovirt-client#207
Yes
Yes
=> Fixes #361: Memory handling

README.md
Removing the warning that the provider is being reworked. It is now available in the [Terraform registry](https://registry.terraform.io/providers/oVirt/ovirt/latest/docs).
Yes
Yes
=> Removing rework warning

docs/resources/vm.md, internal/ovirt/resource_ovirt_vm.go, internal/ovirt/resource_ovirt_vm_test.go
Currently, if `
- ovirt_vm.template_disk_attachment_override.sparse` 
- and/or `ovirt_vm.template_disk_attachment_override.format` 
are not passed or set to null, the terraform state omits those fields. However, the values of those fields are set later on when retrieving them via `data.Get` to the default value of the respective type (e.g. false for bool). 
This PR tries to tackle this issue by introducing "invalid" default values that indicate that those fields have not been set. 
yes
yes
=> added null check for sparse and format

internal/ovirt/resource_ovirt_disk.go, internal/ovirt/resource_ovirt_disk_test.go, internal/ovirt/resource_ovirt_vm.go, internal/ovirt/resource_ovirt_vm_test.go
Currently, if the `memory_ballooning` flag is set to `false`, the default-value check of `GetOk` of the terraform sdk returns the status not found - therefore skipping setting the value. This results in the engine setting the value to the default one (true). This PR attempts to fix this by using the `GetOkExists` function - which should be used carefully. 
https://github.com/hashicorp/terraform/pull/15723
https://github.com/hashicorp/terraform-plugin-sdk/pull/350
yes
yes
=> fix: memory_ballooning for false value properly set

docs/resources/vm.md, internal/ovirt/resource_ovirt_vm.go, internal/ovirt/resource_ovirt_vm_test.go
This way it is possible to deploy a VM directly on another storage domain from Terraform.
Also note that "clone = true" was added, otherwise it's not possible to put a new VM on another datastore.
...
Yes
...
Yes
...
=> Add storage_domain_id to template_disk_attachment_override

docs/resources/vm.md, internal/ovirt/resource_ovirt_vm.go, internal/ovirt/resource_ovirt_vm_test.go
This PR adds a new "initialization_nic" variable that performs cloud-init NIC interface initialization:
```
resource "ovirt_vm" "foo" {
cluster_id  = "%s"
template_id = "%s"
name        = "test"
initialization_hostname = "vm-test-1"
initialization_custom_script = "echo hello"
initialization_nic {
name = "eth0"
ipv4 {
address = "1.2.3.4"
netmask = "255.255.255.0"
gateway = "1.2.3.1"
}
ipv6 {
address = "2001:DB8::12"
netmask = "64"
gateway = "2001:DB8::1"
}
}
}
```
it fixes #493 
I had to update go-ovirt-client, but after using this code in production for a few weeks we didn't notice any obvious issues or regressions
yes
yes
=> Add new option for static IP configuration
