- GNUmakefile
- main.go
- scripts/changelog-links.sh
- scripts/errcheck.sh
- scripts/gofmtcheck.sh
- scripts/gogetcookie.sh
Add missing `GNU make` integration.
> Add GNU make integration

- README.md
This pull request changes the followings:
* Add the newly added Resources: `ovirt_datacenter` and `ovirt_network`
* Add the newly added Data Sources: `ovirt_networks`
* Make the sections of building/installing/using the provider more clear
> Fix outdated readme

- main.tf
- ovirt/data_source_ovirt_storagedomains.go
- ovirt/data_source_ovirt_storagedomains_test.go
- ovirt/provider.go
"squashed" message :)
i broke badly my branch so recreated it anyway now it is single commit :))
> New Data Source: ovirt_storage_domains

- ovirt/resource_ovirt_vm.go
Fix for issue #35 
409 Conflict "[Cannot remove VM with detaching disks, VM is based from template.]"
> fix for issue #35

- ovirt/data_source_ovirt_storagedomains.go
> data/ovirt_storagedomains: Set name_regex optional

- ovirt/resource_ovirt_disk_attachment.go
* Use retry when attaching to a vm, in case of failure due to incorrect vm status
* The timeout is 2 minutes
> resource/ovirt_disk_attachment: Add retry mechanism when attaching to a VM

- ovirt/resource_ovirt_vm.go
* Retry to attach disk when encountering errors, the same to #40 .
Output from the acceptance test:
```
make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtVM_'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtVM_ -timeout 180m
--- PASS: TestAccOvirtVM_basic (94.48s)
PASS
ok  	github.com/EMSL-MSC/terraform-provider-ovirt/ovirt	94.504s
```
> resource/vm: Add retry mechanism when attaching disk

- ovirt/resource_ovirt_vm.go
* Add helper function to shutdown a VM
Basically it try to gracefully  `shutdown` a template-based VM, while if failed to shutdown or no specified template is assigned, it will power off it directly.
> Add helper function for trying to shutdown a VM.

- .travis.yml
- README.md
* Add support for Travis-CI
* Just run `make test`
> Add travis CI support

- main.go
- ovirt/data_source_ovirt_clusters.go
- ovirt/data_source_ovirt_clusters_test.go
- ovirt/data_source_ovirt_common_schema.go
- ovirt/data_source_ovirt_datacenters.go
- ovirt/data_source_ovirt_datacenters_test.go
- ovirt/data_source_ovirt_disks.go
- ovirt/data_source_ovirt_disks_test.go
- ovirt/data_source_ovirt_networks.go
- ovirt/data_source_ovirt_networks_test.go
- ovirt/data_source_ovirt_storagedomains.go
- ovirt/data_source_ovirt_storagedomains_test.go
- ovirt/provider.go
- ovirt/provider_test.go
- ovirt/resource_ovirt_datacenter.go
- ovirt/resource_ovirt_datacenter_test.go
- ovirt/resource_ovirt_disk.go
- ovirt/resource_ovirt_disk_attachment.go
- ovirt/resource_ovirt_disk_test.go
- ovirt/resource_ovirt_network.go
- ovirt/resource_ovirt_vm.go
- ovirt/resource_ovirt_vm_test.go
- ovirt/resource_ovirt_vnic_profile.go
- ovirt/resource_ovirt_vnic_profile_test.go
* Remove `2017 Battelle Memorial Institute` copyright declarations from source codes which are newly added by others
* Add `Joey Ma <majunjiev@gmail.com>` copyrights into some of source codes
> Correct the copyrights according the actual work

- .travis.yml
- README.md
- main.go
- scripts/changelog-links.sh
* Change the references of repository itself from `EMSL-MSC` to `imjoey`
* Change the references of repository itself from `sinokylin` to `imjoey`
See the `Statements` section for more details about this change.
> Relocate the repository and modify related references

- ovirt/resource_ovirt_vm.go
- ovirt/resource_ovirt_vm_test.go
Fixes #59 .
* Add support for memory attribute definition, which is specified in MB unit
* Add a acc test case for memory and other basic VM configurations
```
make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtVM_basic'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtVM_basic -timeout 180m
--- PASS: TestAccOvirtVM_basic (105.82s)
PASS
ok      github.com/imjoey/terraform-provider-ovirt/ovirt        105.845s
```
> resource/ovirt_vm: Enable memory attribute setting

- README.md
* Add `GoReportCard` badge in README
> Add Go Report Card support

- ovirt/provider.go
Hey @imjoey,
I'm sorry but I accidentally introduced a bug in #72.
This PR fixes it, sorry about that! 😑
> Fix headers type assertion

- ovirt/data_source_ovirt_disks.go
- ovirt/resource_ovirt_disk.go
- ovirt/resource_ovirt_disk_test.go
* Add quota configuration when creating a new disk
> resource/ovirt_disk: Add disk quota configuration

- README.md
* Add new resources `ovirt_user` and `ovirt_storage_domain` into readme
* Add new data source `ovirt_authzs` into readme
> readme: Add missing new resources/datasources

- ovirt/provider.go
- ovirt/resource_ovirt_cluster.go
- ovirt/resource_ovirt_cluster_test.go
- ovirt/utils.go
Fixes #82 .
* Add new resource `ovirt_cluster`
```
$ make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtCluster_'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtCluster_ -timeout 180m
=== RUN   TestAccOvirtCluster_basic
--- PASS: TestAccOvirtCluster_basic (1.99s)
PASS
ok  	github.com/imjoey/terraform-provider-ovirt/ovirt	2.015s
```
> New Resource: ovirt_cluster

- README.md
* Add missing new resources/datasources
* Rearrange the items by alphabet order
> doc: Add new resources/datasources in README

- README.md
- ovirt/provider.go
- ovirt/resource_ovirt_tag.go
- ovirt/resource_ovirt_tag_test.go
Fixes #113 .
* Add new resource `ovirt_tag`
```
$ make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtTag_'
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtTag_ -timeout 180m
=== RUN   TestAccOvirtTag_basic
--- PASS: TestAccOvirtTag_basic (3.24s)
PASS
ok      github.com/imjoey/terraform-provider-ovirt/ovirt        3.264s
```
> New Resource: ovirt_tag

- README.md
- ovirt/provider.go
- ovirt/resource_ovirt_host.go
- ovirt/resource_ovirt_host_test.go
Fixes #120 .
* Add basic support for new resource `ovirt_host`
> New Resource: ovirt_host

- ovirt/resource_ovirt_vm.go
- ovirt/resource_ovirt_vm_test.go
Fixes #134 .
* When creating new VM, pass the `memory` parameter only if already set, this would fix the issue described in #134 .
* Explicitly define the suppress function for `memory` attribute, which will ignore the diffs when new `memory` is not set.
> If leaving `memory` blank, `memory` will be automatically set by ovirt engine. As a consequence, differences will be detected that `memory` is going to change from `DEFAULT_MEMORY` (old) to `"0"` (new), which obviously is a mistake.
* Add acceptance testings for `memory` attribute
```
$ make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtVM_memory'
TF_ACC=1 go test …
```
> resource/ovirt_vm: Add explicit suppress diff function for memory attribute

- CHANGELOG.md
* Add missing change logs for v0.2.1
* Add change logs for the upcoming v0.2.2
> Update change logs and preprare for release v0.2.2

- CHANGELOG.md
* Add notes for release `v0.3.0` in CHANGES doc
> Update CHANGES doc for release v0.3.0

- CHANGELOG.md
* Update changes document for release v0.3.1
> Add changes logs for release v0.3.1

- .travis.yml
- README.md
- examples/README.md
- go.mod
- main.go
- scripts/changelog-links.sh
@imjoey @sandrobonazzola please review
> Rename mentions of repo name from imjoey to ovirt

- CHANGELOG.md
> Update change docs for the new release v0.4.0

- CHANGELOG.md
* Add change log for the upcoming new `v0.4.1` release
> Update change log for release v0.4.1

- CHANGELOG.md
> Update CHANGES.doc for new release v0.4.2

- website/docs/r/datacenter.html.markdown
- website/docs/r/disk.html.markdown
- website/docs/r/disk_attachment.html.markdown
- website/docs/r/network.html.markdown
- website/docs/r/snapshot.html.markdown
- website/docs/r/vm.html.markdown
- website/docs/r/vnic.html.markdown
- website/docs/r/vnic_profile.html.markdown
> doc: Improve the expressions

- ovirt/resource_ovirt_vm.go
* Add posibility to edit/update VM parameters (Name, Memory, Cluster, CPU params)
* Added posibility to Start/Stop VM
> Update VM parameters feature and VM running Status

- docs/data-sources/templates.md
- ovirt/data_source_ovirt_template.go
* Add 'latest' option to the template date source, to only return the most recent template.
> Add 'latest' as a flag to data_source_template

- ovirt/resource_ovirt_affinity_group.go
- ovirt/resource_ovirt_affinity_group_test.go
On ocp on RHV we want to add priority to new affinity groups.
Adding priority the created affinity group
> WIP: Add priority to affinity group resource

- ovirt/resource_ovirt_vm.go
* Add `maximum_memory` to set the system maximum memory (up to which memory can be hotswapped in)
> Add maximum_memory field for resource_vm

- ovirt/resource_ovirt_vm.go
* Adds 'lease_domain' to VMs, which sets the HA Lease Domain
> Add lease_domain to VMs, which sets the HA lease domain

- CHANGELOG.md
This PR adds the changelog for the upcoming v4.4.5-r.0 release.
> Changelog for v4.4.5-r.0 release

- ovirt/resource_ovirt_vm.go
This patch will remove the undesired behavior of setting auto pinning
policy to existing when the VM is set with High Performance profile and
not provided with any auto pinning policy input.
The existing policy is going to be blocked in ovirt, we should prevent
users from hitting an error while creating a VM without specifying a
value that might cause it.
> remove auto set existing policy for HP VMs

- .github/workflows/compile-ocp-installer.yml
- tr-ocp-installer.spec
Compiling OCP installer with terraform provider patch changes.
Signed-off-by: Eli Mesika <emesika@redhat.com>
...
...
...
> Compiling OCP installer with patch changes

- ovirt/provider.go
- ovirt/resource_ovirt_vm.go
- ovirt/resource_ovirt_vm_template.go
This change adds utilities needed for [RFE 2035334](https://bugzilla.redhat.com/show_bug.cgi?id=2035334), which enables provisioning OCP nodes with preallocated disks.
Yes
Yes
> Bug 2035334: Preallocated disks for OCP nodes

- ovirt/resource_ovirt_vm_template.go
Fixing the following bug:
resource ovirt_template: description: One of optional, required, or computed must be set
> Fixing resource ovirt_template: description

- docs/_config.yml
- templates/_config.yml.tmpl
This PR adds a theme for publishing on GH pages.
Yes
Yes
> Added config file for publishing GH pages

- .github/workflows/build.yml
Removing CodeQL scanning as it is redundant.
Yes
Yes
> Remove CodeQL scanning

- ovirt/resource_ovirt_disk_from_image.go
gofmt'd resource_ovirt_disk_from_image.go
Yes
Yes
> Reformatting resource_ovirt_disk_from_image.go

- CONTRIBUTING.md
Updating the contributing guide to remove backporting (no longer needed).
Yes
Yes
> Removing backporting section from CONTRIBUTING guide

- ovirt/resource_ovirt_vm.go
This PR is refactoring VM creation for better extensibility.
Yes
Yes
> Refactoring VM creation

- docs/resources/disk_attachment.md
- docs/resources/disk_attachments.md
- docs/resources/nic.md
- docs/resources/tag.md
- docs/resources/template.md
- docs/resources/vm.md
- docs/resources/vm_graphics_consoles.md
- docs/resources/vm_optimize_cpu_settings.md
- docs/resources/vm_start.md
- docs/resources/vm_tag.md
- examples/data-sources/ovirt_disk_attachments/resource.tf
- examples/data-sources/ovirt_template_disk_attachments/resource.tf
- examples/resources/ovirt_disk_attachment/resource.tf
- examples/resources/ovirt_disk_attachments/resource.tf
- examples/resources/ovirt_nic/resource.tf
- examples/resources/ovirt_tag/resource.tf
- examples/resources/ovirt_template/resource.tf
- examples/resources/ovirt_vm/resource.tf
- examples/resources/ovirt_vm_graphics_consoles/resource.tf
- examples/resources/ovirt_vm_optimize_cpu_settings/resource.tf
- examples/resources/ovirt_vm_start/resource.tf
- examples/resources/ovirt_vm_tag/resource.tf
Added examples for the ovirt_blank_template data source.
Yes
Yes
> Examples for ovirt_blank_template resource

- docs/resources/vm.md
- ovirt/resource_ovirt_vm.go
- ovirt/resource_ovirt_vm_test.go
Fixing #389 and adding `cpu_mode` to `ovirt_vm`.
Yes
Yes
> Fixes #389: Adding `cpu_mode` to `ovirt_vm`

- ovirt/resource_ovirt_vm.go
- ovirt/resource_ovirt_vm_test.go
ability to add hostname and custom script with VM first boot (initialization).
Yes
Yes
> fixes #364: introduce customscript and hostname with vm initialization

- .github/workflows/build.yml
Adding permissions for goreleaser.
Yes
Yes
> Added write permissions to goreleaser

- go.mod
- main.go
Moving to /v2 to conform with the Go module specification.
Yes
Yes
> Moved module to /v2 to conform with the Go module specification

- internal/ovirt/resource_ovirt_vm.go
This PR fixes #391 by checking if the vm creation policy feature is supported by the current oVirt version. 
yes
yes
> Fixes #391 - check for vm placement policy feature support

- docs/resources/vm.md
- internal/ovirt/resource_ovirt_vm.go
- internal/ovirt/resource_ovirt_vm_test.go
introduce instance_type_id to ovirt_vm
Yes
Yes
> Fixes #406 - introduce instance_type_id to ovirt_vm resource

- docs/resources/disk.md
- docs/resources/disk_from_image.md
- examples/data-sources/ovirt_blank_template/variables.tf
- examples/data-sources/ovirt_cluster_hosts/variables.tf
- examples/data-sources/ovirt_template_disk_attachments/resource.tf
- examples/data-sources/ovirt_template_disk_attachments/variables.tf
- examples/resources/ovirt_vm_affinity_group/variables.tf
- internal/ovirt/data_source_ovirt_disk_attachments_test.go
- internal/ovirt/data_source_ovirt_template_disk_attachments_test.go
- internal/ovirt/resource_ovirt_disk.go
- internal/ovirt/resource_ovirt_disk_attachment_test.go
- internal/ovirt/resource_ovirt_disk_attachments_test.go
- internal/ovirt/resource_ovirt_disk_from_image.go
- internal/ovirt/resource_ovirt_disk_from_image_test.go
- internal/ovirt/resource_ovirt_disk_test.go
- internal/ovirt/resource_ovirt_template_test.go
- internal/ovirt/resource_ovirt_vm_test.go
This PR fixes the renaming of the `storage_domain_id` field
yes
yes
> fixed renaming storage_domain_id field

- .github/scripts/gogenerate.sh
- .github/workflows/build.yml
Adding a check for `go generate` so we don't forget to make the documentation.
Yes
Yes
> Added go generate check

- internal/ovirt/provider.go
This PR fixes the type casting error which occurs when directly casting the empty interface returned from `data.GetOk` to a slice of strings. 
yes
yes
> fixed type casting error when directly casting an empty interface to slice of strings

- .github/workflows/build.yml
This PR makes the `go generate` step required.
Yes
Yes
> Make the go generate step required

- internal/ovirt/data_source_templates.go
- internal/ovirt/data_source_templates_test.go
- internal/ovirt/provider.go
Adding the `ovirt_templates` data source.
Yes
Yes
> Added `ovirt_templates` data source

- internal/ovirt/resource_ovirt_vm.go
In this PR switched the `RequiredWith` condition for the fields `memory` and `maximum_memory`
yes
yes
> switched field requirement for maximum_memory and memory

- .github/workflows/build.yml
Replaces broken Hashicorp GPG import action with an inline version
Yes
Yes
> Replace GPG key import

- .github/workflows/build.yml
This PR fixes the bad substitution issue in the import gpg key build step
yes
yes
> fixed bad substitution import gpg key build step

- .github/workflows/build.yml
This PR updates the [GoReleaser](https://github.com/goreleaser/goreleaser-action) from v2 to v3
yes
yes
> updated goreleaser

- .github/workflows/build.yml
This PR attempts to fix the gpg signing issue. 
yes
yes
> fix gpg signing

- .github/workflows/build.yml
- .goreleaser.yml
This PR is an attempt to fix the gpg signing. 
yes
yes
> fixed gpg signing

- go.mod
- go.sum
This PR updates the `go-ovirt-client` dependency. 
yes
yes
> bump go-ovirt-client version

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature_request.md
Update default assignee
yes
yes
> update default assignee

- .github/workflows/build.yml
- .github/workflows/tr-master-suite-trigger.yaml
- .golangci.yml
Update all action versions and build on the latest Go version.
> ci: update action versions

- examples/examples_test.go
- internal/ovirt/data_source_affinity_group.go
- internal/ovirt/data_source_ovirt_disk_attachments.go
- internal/ovirt/data_source_ovirt_template_disk_attachments.go
- internal/ovirt/resource_ovirt_affinity_group.go
- internal/ovirt/resource_ovirt_disk.go
- internal/ovirt/resource_ovirt_disk_from_image.go
- internal/ovirt/resource_ovirt_disk_resize.go
- internal/ovirt/resource_ovirt_disk_test.go
- internal/ovirt/resource_ovirt_tag.go
- internal/ovirt/resource_ovirt_vm.go
- internal/ovirt/resource_ovirt_vm_affinity_group.go
- internal/ovirt/resource_ovirt_vm_disks_resize.go
- internal/ovirt/resource_ovirt_vm_disks_resize_test.go
- internal/ovirt/resource_ovirt_vm_graphics_consoles.go
- internal/ovirt/resource_ovirt_vm_tag.go
- internal/ovirt/resource_ovirt_vm_test.go
- scripts/get_test_image/get_test_image.go
Fixing the current gosec lint issues related examples_test.go, actually I suppressed them because the code architecture is right.
Yes
Yes
> Fix lint security issues related to examples_test.go
